### PR TITLE
Add application password auth flow

### LINKED ISSUE #286: Feature: Easier setup flow for Application Passwords & External connections
Since https://github.com/georgestephanis/application-passwords/pull/39#issuecomment-283677076 Application Password supports a much easier flow when setting up an application password. Distributor can link to the remote site with a special URL that lets the user create the new key on the fly, during the setup flow. 

Implementing this flow would make external connection setup much smoother.

From the PR:
> The idea is to give a page in wp-admin where you can send a user, they can authenticate via wp-login.php if needed, then manually approve (or reject) it and it will send the user back to the app with an application password in tow that the app can store and use.

> It saves the user from having to find their profile page and create and retype or copy/paste an application password. Should be more understandable.

### PR DESCRIPTION
**Pull request by adamsilverstein**
Resolves #286

### CODE REVIEW

**Comment by jeffpaul** [comment]
@adamsilverstein once you feel this is solid, we should test for the following issues to see if we appear to resolve their problems.  After release, I can coordinate with each (and anyone who happens to be subscribed to the issue and responds to my update therein) to see if it helps (1) resolve their issues or (2) better surfaces the specific error in their connection setup: #45, #79, #164, #209, #244, #246, #295, #299, #315, #327, #338, and #347.

**Comment by adamsilverstein** [comment]
This is ready for some testing/review.

**Comment by adamsilverstein** [comment]
I will work to address the broken e2e tests - changes to the external connection screen broke the tests.

**Comment by adamsilverstein** [comment]
Closing this as I rework with a new approach with less impact (eg code changes) on the existing setup screen.

**Pull request closed without merging**
