### PR TITLE
Release: 2.0.0

### LINKED ISSUE #1118: The plugin hasn't been tested with the latest version of WordPress
There is a new WordPress version that the plugin hasn't been tested with. Please test it and then change the "Tested up to" field in the plugin readme.

**Tested up to:** 6.2
**Latest version:** 6.3

This issue will be closed automatically when the versions match.

### PR DESCRIPTION
**Pull request by dkotter**
- [x] Branch: Starting from `develop`, create a release branch named `release/2.0.0` for your changes.
- [x] Version bump: Bump the version number in `distributor.php`, `package.json`, `package-lock.json`, `readme.txt` and `tests/php/bootstrap.php` if it does not already reflect the version being released.  In `distributor.php` update both the plugin "Version:" property and the plugin `DT_VERSION` constant.
- [x] New files: Ensure any new files, especially in the vendor folder, are correctly included in `webpack.config.release.js`.
- [x] Changelog: Add/update the changelog in `CHANGELOG.md`.
- [x] Props: Update `CREDITS.md` file with any new contributors, confirm maintainers are accurate.
- [x] Readme updates: Make any other readme changes as necessary.  `README.md` is geared toward GitHub and `readme.txt` contains WordPress.org-specific content.  The two are slightly different.
- [x] Since tag updates: ensure `@since` tags indicate the new version, replacing `x.x.x`, `n.e.x.t` and other placeholders.
- [x] Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the Pull Request), then do the same for `develop` into `trunk` (`git checkout develop && git pull origin develop && git checkout trunk && git merge --no-ff develop`).  `trunk` contains the stable development version.
- [x] Build: Wait for the [Build Stable Release Action](https://github.com/10up/distributor/actions?query=workflow%3A%22Build+Stable+Release%22) to finish running.
- [x] Review: Do a review of the commit to the `stable` branch to ensure the contents of the diffs are as expected.
- [x] Test: Check out the `stable` branch and test it locally to ensure everything works as expected.  It is recommended that you rename the existing `distributor` directory and check out `stable` fresh because switching branches does not delete files.  This can be done with `git clone --single-branch --branch stable git@github.com:10up/distributor.git`
- [x] Release: Create a [new release](https://github.com/10up/distributor/releases/new), naming the tag and the release with the new version number, and **targeting the `stable` branch**.  Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the [closed issues on the milestone](https://github.com/10up/distributor/milestone/20?closed=1).  The release should now appear under [releases](https://github.com/10up/distributor/releases).
- [ ] Check release: Wait for the [Publish Release Action](https://github.com/10up/distributor/actions?query=workflow%3A%22Publish+Release%22) to complete, and then check the latest release to ensure that the ZIP has been attached as an asset.  Download the ZIP and inspect the contents to be sure they match the contents of the `stable` branch.
- [ ] Close milestone: Edit the [milestone](https://github.com/10up/distributor/milestone/20) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description` field), then close the milestone.
- [ ] Punt incomplete items: If any open issues or PRs which were milestoned for `2.0.0` do not make it into the release, update their milestone to `2.0.1`, `2.1.0`, or `Future Release`.

### CODE REVIEW

**Comment by dkotter** [comment]
E2E tests that are running on WP 6.3 are failing due to the change in 6.3 where the Block Editor is loaded in an iframe by default. Cypress won't load the contents of the iframe by default but you can get around this with a config value (which I added [here](https://github.com/10up/distributor/pull/1123/commits/56e3fd445b6eaaf7135285e7ef8450d369ab0228)).

But in addition to that, any interaction that we do with the editor needs to account for the editor being in an iframe. For example, any use of `cy.createPost` will no longer work. I originally contemplated trying to fix all of that here but I think this should probably be handled in a separate PR, as well as some of these changes need to happen in our Cypress WP Utils package.

**Comment by jeffpaul** [comment]
@dkotter given the Migration guide for v1 > v2 is relatively light on need, but perhaps we should still call that out here in the CHANGELOG.md as another sentence linking to that guide for folks to reference in their upgrades?  If its significant enough of a migration need, then we might also have an admin notice that references it perhaps?

**Comment by dkotter** [comment]
> @dkotter given the Migration guide for v1 > v2 is relatively light on need, but perhaps we should still call that out here in the CHANGELOG.md as another sentence linking to that guide for folks to reference in their upgrades? If its significant enough of a migration need, then we might also have an admin notice that references it perhaps?

I've added links to the CHANGELOG and README files for that migration guide. I don't think it warrants an admin notice, especially since the few things we call out are more developer type things which an admin may not have the ability/access to do anything there.

**Review by jeffpaul — DISMISSED** [review]
Still [some other items in the v2 milestone](https://github.com/10up/distributor/milestones/2.0.0), but nothing that I would fight people for to get into this release so approving this release PR as-is... very exciting!

**Comment by peterwilsoncc** [comment]
For the migration guide, these are possible things we should call out:

* Minimum requirements bump: WP and PHP
* REST API changes to Distributor endpoints (hopefully people are not using these)
   * different structure 
   * requests from Dist < 1.x effectively blocked
* Translations now include strings in JavaScript files
* `dt_push_post` hook deprecated in favour of `dt_push_external_post` and `dt_push_network_post` due to parameter conflicts

**Comment by jeffpaul** [comment]
@peterwilsoncc is there an update to the hookdocs page and the changelog that you could push up here?

**Comment by jeffpaul** [comment]
@dkotter seems like we can probably bump the WP "tested up to" 6.3 here as well and set the PR to similarly close #1118, yeah?

**Comment by peterwilsoncc** [comment]
@jeffpaul @dkotter I've pushed some updates to the migration guide to cover the items listed above.

**Review by jeffpaul — DISMISSED** [review]

**Comment by peterwilsoncc** [comment]
@jeffpaul I think this is good to go, once Darin and I figure out some line ending differences in #1124 so `composer install` doesn't end up creating changes on some systems but not others.

**Review by peterwilsoncc — DISMISSED** [review]
E2E tests failures are due to the iframed post editor (`.block-editor-default-block-appender__content` exists but not in the DOM tree Cypress has access too).

In some Gutenberg tests for the PR iframing the post editor, [a dummy block was created](https://github.com/WordPress/gutenberg/pull/48286/commits/210fafc7b9a5c3ead06f34815d224ed5debe5910) to prevent the iframe from being initiated. Perhaps we could do that but I don't think it's a blocker for release.

**Review by peterwilsoncc — APPROVED** [review]
Reapprove following change log update.

**Pull request merged**
