### PR TITLE
Apply filter to modify connection cpt arguments

### LINKED ISSUE #394: Add hook to modify connection cpt arguments
Created another PR to add `dt_before_setup_cpt` filter to make possible to modify `dt_ext_connection` custom post type arguments.

### PR DESCRIPTION
**Pull request by avag-novembit**
Added `dt_before_setup_cpt` filter to make possible to modify `dt_ext_connection` custom post type arguments (closes #394).

### CODE REVIEW

**Comment by jeffpaul** [comment]
@adamsilverstein @dkotter if either of you have time to review this that would be great, thanks!

**Comment by jeffpaul** [comment]
@avag-novembit it looks like this PR includes work from PR #384 and #386, mind stripping that duplicate stuff out so that this PR only includes code related to issue #394?

**Comment by avag-novembit** [comment]
Fixed, sorry about that.

**Comment by dinhtungdu** [comment]
@jeffpaul let's close this PR (and issue #394) because we can use `register_post_type_args` to alter post type arguments. See https://github.com/10up/distributor/issues/394#issuecomment-509676718

**Comment by jeffpaul** [comment]
Agreed, closing in favor of using the `register_post_type_args` filter.

**Pull request closed without merging**
