### PR TITLE
Fix "Limited connection" issue

### LINKED ISSUE #457: Showing "Limited connection established. Authentication failed" for authenticated connections
**Describe the bug**

Showing "Limited connection established. Authentication failed" message for authenticated connections on the "Edit External Connection" page.

**Steps to Reproduce**

1. Go to 'wp-admin > Distribution > External Connections'
2. Click on 'Verify' of the previously created external connection.
3. After opening "Edit External Connection" page scroll down to the "External Connection URL", where after "Checking endpoint" shows message "Limited connection established. Authentication failed" though the authentication was successful.

**Expected behavior**

In the mentioned section should show up "Connection established" message in case authentication was successful.

**Screenshots**

connection-error

Here we can see that authentication was successful by judging by "dt_verify_external_connection" AJAX response, though we see "Limited connection established. Authentication failed" message.

**Environment information**
 - OS: Windows 10 Pro
 - Browser and version: Chrome, 76.0.3809.132 (latest)
 - Distributor version: 1.5.0 (latest)

**Additional context**

This behavior comes from `distributor/assets/js/admin-external-connection.js` line 86, where we have:

    if ( response.data.errors.no_distributor || ! response.data.can_post.length ) {

though `response.data.can_post` is an object, and we should use instead:

    if ( response.data.errors.no_distributor || ! Object.keys( response.data.can_post ).length ) {

I'm going to create a PR which fixes the issue.

### PR DESCRIPTION
**Pull request by avag-novembit**
Fix showing "Limited connection established. Authentication failed" for authenticated connections issue.
closes #457

### CODE REVIEW

**Comment by adamsilverstein** [comment]
Hey @avag-novembit thanks for your contribution!

Looking at the endpoint where this data is constructed, `can_post` should be an array, at least it is constructed that way: https://github.com/10up/distributor/blob/bcc1527a50f315852bb9a1985328c35737f86b65/includes/classes/ExternalConnections/WordPressExternalConnection.php#L883.

I'm curious if this worked for you previously or if anything changed on your end that caused this to start failing? Is there anything unique about your remote sites that might change the API response?

I will test this locally to see if I can reproduce.

**Comment by avag-novembit** [comment]
@adamsilverstein thanks for the response.

I see. Let me check this and get back to you.

**Comment by avag-novembit** [comment]
Indeed `can_post`, `can_get` are arrays, there are modifications in the our fork which I missed, sorry about that. I think we can close this.

**Comment by adamsilverstein** [comment]
No worries, thanks for the bug report @avag-novembit - we appreciate active users who take the time to report bugs (even if they turn out to be false reports)!

**Pull request closed without merging**
