### PR TITLE
Fix: wrong permission route

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
The permission route in #245 which was merged to `develop` is wrong, that causes creating external connections failed. This PR fixes the URL and adds more checks to prevent potential warnings and errors.

### Verification Process
See the tests pass.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/distributor/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jeffpaul** [comment]
I wonder if this may be why @dkotter and @helen are having different results in testing #368, assuming Helen pulled develop down after #245 was merged and Darin before?

**Comment by dinhtungdu** [comment]
@jeffpaul I don't think so, that issue relates to Application Password load order.

**Comment by dkotter** [comment]
@dinhtungdu Testing this out, I had an issue where it would connect to an external connection but wouldn't give me the proper message (gave me the yellow light instead of the green). Tracked down the issue and the problem was with the array we return to our ajax function. The array keys needed reset, otherwise it ended up as a javascript object and not an array, which was breaking our javascript functionality.

I've made that fix, as well as some minor code formatting fixes (that were mostly from the original PR). This looks good to me now.

**Comment by dkotter** [comment]
@dinhtungdu Testing this out, I had an issue where it would connect to an external connection but wouldn't give me the proper message (gave me the yellow light instead of the green). Tracked down the issue and the problem was with the array we return to our ajax function. The array keys needed reset, otherwise it ended up as a javascript object and not an array, which was breaking our javascript functionality.

I've made that fix, as well as some minor code formatting fixes (that were mostly from the original PR). This looks good to me now.

**Review by dkotter — APPROVED** [review]

**Comment by dkotter** [comment]
And just for performance numbers, on my local install, I saw these external connection test requests go from 8-9 seconds down to 1.5-2 seconds, so a pretty nice improvement there.

**Pull request merged**
