### PR TITLE
Add WordPress Playground blueprint

### LINKED ISSUE #1266: Add WordPress Playground integration
### Is your enhancement related to a problem? Please describe.

- [ ] add blueprint to github folder
- [ ] add repo badge to playground

Note that we'll want to set up the playground as a multisite, not fully certain that's yet possible so if not let's open an issue upstream in the playground repo and then mark this as blocked by that.

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dottxado**
### Description of the Change
I added the WordPress Playground blueprint that permits to spin up a WordPress instance and demonstrates the Distributor plugin in action. The blueprint ships an environment with the following:
- multisite active and two websites created
- the plugin installed and activated at network level

Closes #1266

:warning: An important note: the blueprint installs the plugin from the stable branch, but in the documentation I built the example URL pointing to the `develop` branch (which is where this PR is pointing to). I don't know if you prefer the example URL to target the stable branch, so please let me know!

### How to test the Change
You can test the blueprint by following [this link](https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/dottxado/distributor/refs/heads/add-blueprint/docs/blueprint.json)

### Credits
Props @dottxado

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by dkotter — CHANGES_REQUESTED** [review]
Thanks for getting this working, looks really good!

Two things I'd suggest:

1. When the Playground is ready, it just lands you on the homepage of the main site. I think landing you on one of the Distributor settings screens would be a better demo experience, maybe `/wp-admin/admin.php?page=pull`? Or maybe just a single post in the admin, giving a user quick access to try pushing content?
2. Would be great to add a badge to the readme file that links to the Playground. Can see an example of that [here](https://github.com/10up/classifai/pull/814/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R5)

**Comment by dottxado** [comment]
Hello @dkotter!
Thanks for the feedback, I added the badge and the landing page. About this last change, I wanted to suggest to add some content with WP-CLI ready to be distributed (and not relying only the "Hello world" default one), but I am not finding a proper way, and I also would like to not overcomplicate the blueprint only to create some content.

Please let me know if you want me to move the bluprint.json file to another folder: from the [classifai PR](https://github.com/10up/classifai/pull/814/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R5) I see it has been loaded in the .github folder.

**Comment by jeffpaul** [comment]
If additional content is desired, perhaps using [starter content](https://make.wordpress.org/core/2016/11/30/starter-content-for-themes-in-4-7/) might help there?

**Comment by dottxado** [comment]
Hello @jeffpaul!
In my opinion, the problem with the solutions I have considered is overengineering, and I don't think the game is worth it, in terms of the readability and maintainability of the blueprint :thinking: 

I have tested the following setups:
- a WP-CLI step that creates a demo post in the second website: it doesn't work because I need to provide the website full URL that I don't know. I tried to compose WP-CLI commands to obtain the URL but, without surprise, it wasn't working
- a WP-CLI step that creates a demo post on the first website while the blueprint lands the user in the dashboard of the second: WordPress is loaded on the 404 page. Manually I can navigate to the dashboard and everything works, so it is not really clear why it isn't working automatically.


The nearest solution I can provide with a small footprint on the blueprint is like the last one, but instead of using the dashboard as a landing page, I can land you on the homepage of the second website. [This is an example if you want to test](https://playground.wordpress.net/#ewogICIkc2NoZW1hIjogImh0dHBzOi8vcGxheWdyb3VuZC53b3JkcHJlc3MubmV0L2JsdWVwcmludC1zY2hlbWEuanNvbiIsCiAgInBocEV4dGVuc2lvbkJ1bmRsZXMiOiBbCiAgICAia2l0Y2hlbi1zaW5rIgogIF0sCiAgImZlYXR1cmVzIjogewogICAgIm5ldHdvcmtpbmciOiB0cnVlCiAgfSwKICAibGFuZGluZ1BhZ2UiOiAiL3Rlc3QiLAogICJzdGVwcyI6IFsKICAgIHsKICAgICAgInN0ZXAiOiAiaW5zdGFsbFBsdWdpbiIsCiAgICAgICJwbHVnaW5EYXRhIjogewogICAgICAgICJyZXNvdXJjZSI6ICJ1cmwiLAogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly9naXRodWItcHJveHkuY29tL3Byb3h5Lz9yZXBvPTEwdXAvZGlzdHJpYnV0b3ImYnJhbmNoPXN0YWJsZSIKICAgICAgfQogICAgfSwKICAgIHsKICAgICAgInN0ZXAiOiAiZW5hYmxlTXVsdGlzaXRlIgogICAgfSwKICAgIHsKICAgICAgInN0ZXAiOiAid3AtY2xpIiwKICAgICAgImNvbW1hbmQiOiAid3AgcGx1Z2luIGFjdGl2YXRlIGRpc3RyaWJ1dG9yLXN0YWJsZSAtLW5ldHdvcmsiCiAgICB9LAogICAgewogICAgICAic3RlcCI6ICJ3cC1jbGkiLAogICAgICAiY29tbWFuZCI6ICJ3cCBzaXRlIGNyZWF0ZSAtLXNsdWc9dGVzdCIKICAgIH0sCiAgICB7CiAgICAgICJzdGVwIjogIndwLWNsaSIsCiAgICAgICJjb21tYW5kIjogIndwIHBvc3QgY3JlYXRlIC0tcG9zdF90eXBlPXBvc3QgLS1wb3N0X3RpdGxlPSdBIHNhbXBsZSBwb3N0IHRvIGJlIGRpc3RyaWJ1dGVkJyIKICAgIH0KICBdCn0K)
And these are the changes in the blueprint:
```diff
- "landingPage": "/wp-admin/admin.php?page=pull",
+ "landingPage": "/test",
.
.
.
+    {
+      "step": "wp-cli",
+     "command": "wp post create --post_type=post --post_title='A sample post to be distributed'"
+    }
```


Every other setup I thought of requires writing a plugin to insert content into the second website, while the blueprint can land you in the dashboard of the first website. Is it worth having such a portion of code inside the blueprint? Also, this idea is untested, so I don't even know if it will work :woman_shrugging: 
Sounds to me that the issues I have encountered will be fixed in the future (maybe I can open some issues to track them), so I don't think that this amount of overengineering is needed :smile: 
Let me know your thoughts!

**Comment by dkotter** [comment]
@dottxado This looks good to me and I agree that we can look to make additional changes to the content in the future if we decide that's worth the effort. For now this at least gets a demo environment working

**Review by dkotter — APPROVED** [review]

**Comment by dottxado** [comment]
Cool, thank you very much for having me contribute, @dkotter! :smile: 
Can I ask you if you can add the `hacktoberfest-accepted` label? :bow:

**Comment by jeffpaul** [comment]
Sharing some notes here on leveraging Starter Content to get some example posts/pages onto the multisite, perhaps even some that show posts already in a push and pull state as examples for folks (maybe going even further with skipped in the pull state).

> **Two new blueprints in the Gallery:** ImportStarter Content
>
> Since [WordPress 4.7](https://gutenbergtimes.us1.list-manage.com/track/click?u=e3062ef0fb204dbbc2135b555&id=31e213a392&e=6ccb836842), Theme builders could add Starter Content to their themes, to showcase how the theme could shine or to give users a head start on building their new site. Playground offers two methods to import Starter Content: via an [option on the installTheme step](https://gutenbergtimes.us1.list-manage.com/track/click?u=e3062ef0fb204dbbc2135b555&id=6a93925577&e=6ccb836842) or as a separate importStarterContent step. The two new examples in the [Blueprint Gallery ](https://gutenbergtimes.us1.list-manage.com/track/click?u=e3062ef0fb204dbbc2135b555&id=8dfab5afc8&e=6ccb836842)show how to use both of them.
>
> startercontent

**Pull request merged**
