### PR TITLE
Fix duplication of terms

### PR DESCRIPTION
**Pull request by arsendovlatyan**
Fix duplication of terms with every update, in case if term slug is custom set in source website and term creation is not disabled/skipped with hooks in destination. #261

### CODE REVIEW

**Comment by jeffpaul** [comment]
@arsendovlatyan it looks like the build failed on these changes, mind giving those a review to try and ensure this build passes?

**Comment by jeffpaul** [comment]
Resolves #325.

**Comment by jeffpaul** [comment]
@adamsilverstein @dkotter if either of you have time to review this that would be great, thanks!

**Comment by helen** [comment]
I cannot figure out why it's reporting whitespace at the end of line 447 and not reporting the warnings at line 490 that I get locally. Merging, will deal with it separately if necessary.

**Comment by arsendovlatyan** [comment]
Thank you very much @helen , will try to be more accurate with code and cover with tests as well.

**Pull request merged**
