### PR TITLE
Add view all post types filter to External Connections.

### LINKED ISSUE #861: Add ability to view all post types when Pulling from an External Connection
### Is your enhancement related to a problem? Please describe.

When you go to the Pull screen for an Internal/Network Connection, we default to showing content from all supported post types. You can then filter down to just the post type you want (like Posts).

But for External Connections, we default to showing just Posts and there isn't a way to view content across all post types. This is because historically we were requesting content from a post type specific endpoint, so it was impossible to get content across multiple post types. But with the changes introduced in #811, we can now show content from across all supported post types, mirroring how we do this for Internal Connections.

One thing to note here is if you are on an External Connection that has had no content pulled or skipped yet, we utilize the old approach to grabbing content, from a post type specific endpoint and not the new endpoint introduced in #811. So that will need to be addressed here to fully support his new feature.

Screen Shot 2022-03-08 at 4 17 06 PM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ankitrox**
### Description of the Change

Introduce a "View All" post type view to the pull screen for external connections for parity with the internal connections. The new view is the default when visiting Distributor > Pull Content > [External connection].

Closes #861 

### How to test the Change

1. Create two separate sites using insta wp.
2. Install distributor plugin on both the sites. Connect the sites.
3. Create a custom post type "Book" on both the sites.
4. On pull screen ensure that "View All" option is available.
5. Pull content from CPT and it should pull the posts from external sites.

### Changelog Entry

> Added - Introduce "View all" post type view when pulling content from external connections.

### Credits

Props @ankitrox, @Sidsector9, @ravinderk, @jeffpaul, @peterwilsoncc 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by jeffpaul** [comment]
Tagging Max on this one as he's already reviewed a separate PR #1002 for the same issue, so worth checking here to see which approach is most optimal (and can close the lessor of the two)

**Comment by Sidsector9** [comment]
@ankitrox can you please fill up the description and testing instructions for clarity?

**Comment by ankitrox** [comment]
> @ankitrox can you please fill up the description and testing instructions for clarity?

Added the steps to test

**Review by Sidsector9 — CHANGES_REQUESTED** [review]
Hi @ankitrox 

I followed your instructions and tested this branch, I faced some issues. The Posts filter shows Pages as well.

I tested by resolving the conflicts locally as well and still faced the same issue.

Please watch the video below:

https://github.com/10up/distributor/assets/17757960/7bfb0b6a-6caf-43ed-9277-54f3fdb70d09

Let me know if I'm missing any steps.

**Comment by peterwilsoncc** [comment]
The changes in `develop` to the `includes/rest-api.php` file are causing a few conflicts for this. 

However, the good news is that the changes allow for requesting `any` as the post type to get all the post types so you won't need to make any changes to the file -- the other files will need to specify the post type as `any` rather than `all`.

**Review by peterwilsoncc — COMMENTED** [review]
I've pushed a few changes to account for updates to the REST API endpoint in Distributor 2.0.0

For external connections, I am wondering if it would be best to send the local post types individually when requesting `all` post types: this will allow for situations in which the external connection has post types that are not supported locally.

However, I think that might be best left fro another ticket.

**Review by ravinderk — CHANGES_REQUESTED** [review]
@peterwilsoncc I am not getting a correct result for the `View all` filter.

I noticed that in the final SQL query, WordPress adds `post_author` to the current user id (rest API) when doing a query for multiple posts (i.e. `all`), which means I am not getting the list of all editable posts from all post types.

Can you check?
 
image
image

**Review by peterwilsoncc — DISMISSED** [review]
> I noticed that in the final SQL query, WordPress adds `post_author` to the current user id (rest API) when doing a query for multiple posts (i.e. `all`), which means I am not getting the list of all editable posts from all post types.

I'm not seeing this issue when connected as an administrator. If Ravinder had connected the sites as a non-admin it may be an effect of the security fixes in https://github.com/10up/distributor/security/advisories/GHSA-q43c-v867-4cfp 

I think this code is good or merging.

**Comment by jeffpaul** [comment]
Closing in favor of #1002.

**Pull request closed without merging**
