### PR TITLE
add `dt_syndicatable_capabilities` filter to push ui

### PR DESCRIPTION
**Pull request by pragmatic-tf**
### Description of the Change

Adds a new filter to the user capability check found in the `syndicatable()` function, which controls access to the Push UI in the WP admin bar.

### Alternate Designs

N/A

### Benefits

This will allow other plugins to dynamically update the capability required to enable the push UI in the WP admin bar.

### Possible Drawbacks

None that I can foresee - the code addition doesn't alter any existing functionality by itself.

### Verification Process
After applying the code change, I tested the filter on a local development install by changing the capability to allow different user roles access to the Push UI.

- Changing the capability to `read` allowed a test Subscriber to use the Push UI
- Changing the capability to `edit_published_posts` prevented a test Contributor from using the Push UI but still allowed a test Author to use it.
- Changing the capability to a custom capability - `dt_test_cap` - prevented any users from accessing the Push UI, except super-admins.
- Adding the `dt_test_cap` custom capability to the Author role, then allowed a test Author to access the Push UI.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/distributor/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues
See: #472

### CODE REVIEW

**Comment by pragmatic-tf** [comment]
Just checking in on this PR - looks like the CI build is failing but I'm not too sure why... Is there anything I can do (or need to change) to help it pass the appropriate checks?

I also popped a question on issue #473 about documentation - is the inline code doc block enough or is there another place I should document the new filter?

**Comment by jeffpaul** [comment]
@pragmatic-tf the doc block _should_ be sufficient, as once that gets merged it should appear on our technical documentation site: https://10up.github.io/distributor/.  As for the failing build, I'm uncertain what's going on there and will see if we can figure that out while reviewing this PR.  Thanks for checking in and for the PR, happy holidays!

**Review by dinhtungdu — COMMENTED** [review]
`capabilities` is a plural word, so from the filter name, I would expect passing multiple capabilities to this filter. We have two options here:

- change the filter name to the singular
- or change the code to handle multiple capabilities

cc @jeffpaul

**Comment by pragmatic-tf** [comment]
Hey @dinhtungdu 👋 totally get where you're coming from, and it's a good point.

 Use of the plural was in order to stay consistent with a few other capability filters in the rest of the plugin codebase:
`dt_capabilities`
`dt_external_capabilities`
`dt_pull_capabilities`
`dt_push_capabilities`

☝️ The above all handle single capability filters, but use the plural, so it all depends on whether the preference is to maintain consistency or go for semantic correctness? More than happy to update the PR for either.

It's worth noting that `current_user_can()` doesn't accept multiple capabilities so that's not a possible solution unfortunately.

**Review by dinhtungdu — APPROVED** [review]
@pragmatic-tf thanks for the head up, I haven't checked the naming convention, so I'm changing my review now.

About the multiple capabilities, we can do it by looping through the array and apply `current_user_can` for each but it will break the current convention, so let's ignore it for now.

**Pull request merged**
