### PR TITLE
WIP: Update Notices to latest Gutenberg Package

### PR DESCRIPTION
**Pull request by JasonHoffmann**
Brought up in #252 

This changes the way notices are generated, passing plain text strings and a series of actions, instead of creating a dynamic element and passing it to `createWarningNotice`. Most of the text remains the same in the notices, but some of  the nomenclature has to be shifted.

Here are the three states:
screen shot 2018-11-16 at 8 27 31 am

screen shot 2018-11-16 at 8 28 03 am

screen shot 2018-11-16 at 8 36 21 am

### CODE REVIEW

**Comment by helen** [comment]
Looks like we've lost the link to the original post in the `Originally distributed from X` string. Otherwise the PR looks good, the internationalization is done incorrectly but that is not your fault (see #267).

**Comment by JasonHoffmann** [comment]
@helen thanks for reviewing. I've added that original post link back into the actions. Are there any steps to take in terms of proper internationalization yet, or is that still being sorted out?

**Comment by helen** [comment]
@JasonHoffmann Thanks for the update, this looks good now so I'll get it merged! I haven't yet outlined specific steps for fixing up internationalization, is that something you'd be interested in?

**Comment by JasonHoffmann** [comment]
@helen I think I could help out with that. I could at least help sort out the build process and fix up some strings, once you've decided what the best way to approach the issue is.

**Pull request merged**
