### PR TITLE
Update all packages & build

### PR DESCRIPTION
**Pull request by adamsilverstein**
### Description of the Change
* Update all packages to their latest version, replacing deprecated packages.
* Use postcss for cssnano processing.
* Address ESLint warnings/errors: array destructuring & string concatenation.
* Update `Gulp` tasks to new version 4 setup, returning promises.
* Address `runSequence` deprecation with `gulp4-run-sequence`.
* Ensure local Gulp is used when running `npm run build`
* Explicitly set webpack mode to `production`.

### Verification Process

These changes need thorough testing:

* Build the plugin - `npm install && npm run build`
* Test all functionality, especially reviewing JavaScript and CSS for any changes
* Test across supported browsers

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/10up/distributor/blob/develop/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by adamsilverstein** [comment]
I will look into the failing tests and make sure everything is up to date here.

**Comment by adamsilverstein** [comment]
Note: review without whitespace: https://github.com/10up/distributor/pull/450/files?w=1

**Review by dkotter — DISMISSED** [review]

**Comment by dkotter** [comment]
This looks good to me from a code level, as well as testing locally. One thing to note, we are updating to a newer version of ESLint that requires a new [minimum version of Node](https://eslint.org/docs/user-guide/migrating-to-6.0.0#drop-node-6). I was using an older version locally and compiling didn't work until I updated. Not sure if this is something we want to document and if so, not sure the best place to do that.

**Comment by jeffpaul** [comment]
@dkotter as noted today with @dinhtungdu, let's update that in package.json and I'll open a separate PR to call that out in README.md in a new Developers section.

**Comment by dkotter** [comment]
I've added the minimum version to our `package.json` file.

**Review by dkotter — APPROVED** [review]

**Comment by jeffpaul** [comment]
Awesome, let's go ahead and merge this in thanks for the review!

**Pull request merged**
