### PR TITLE
Feature - localize distributed attachments in post content

### LINKED ISSUE #372: Distributed post attachments localization
First of all thank you for the great plug-in!

Currently, attachments in distributed post content are linked back to the hub [from where distributed]. As currently there is a functionality to distribute post attachments as well, I think it would be better to replace the attachments' URL-s in the post content so they reference to current site (use the distributed attachments in post content).

I'll will go ahead and send a pull request with that functionality.

### PR DESCRIPTION
**Pull request by avag-novembit**
Localizing distributed post attachments so they will be referenced to the distributed attachments instead of the ones on the "hub" website. 
Closes #372 .

### CODE REVIEW

**Comment by jeffpaul** [comment]
@adamsilverstein @dkotter if either of you have time to review this that would be great, thanks!

**Comment by dinhtungdu** [comment]
@avag-novembit This PR has a conflict file too, please fix it so we can review this! Thank you!

**Comment by arsendovlatyan** [comment]
Hey @dinhtungdu ,
@avag-novembit  is no longer working on this project, but I'll ask @armdev17 to review and update this PR.

**Comment by jeffpaul** [comment]
Unassigning reviewers here while we focus on the v2 refactoring and can then reassess how best to handle the root issue here.

**Comment by jeffpaul** [comment]
Closing this as the conflicts are unfortunately dated because our slow response, but in testing things I am seeing that the media distribution (of non-featured images) is in fact not working so we'll look to get this replaced with a separate PR and credit folks here for the work in that new PR.

**Pull request closed without merging**
