### PR TITLE
Feature: test against multiple snapshot variations

### PR DESCRIPTION
**Pull request by adamsilverstein**
Note: requires https://github.com/10up/wpacceptance/pull/4

Tests against:

* WordPress 4.9.9
* WordPress 4.9.9 plus Gutenberg 4.9
* WordPress 5.1.0
* WordPress 5.1.0 plus Gutenberg 5.2.0

### CODE REVIEW

**Comment by adamsilverstein** [comment]
Tests are passing in GB/non GB now, for some reason the tests only run on the first machine, the others fail to load and throw an error: https://travis-ci.org/10up/distributor/builds/514895215

image

I experience the same testing locally - only the first snapshot in the array runs the tests correctly. @tlovett1 could you please take a look at this when you have a moment to see if you can figure out why the `snapshots` array fails after the first snapshot?

**Comment by adamsilverstein** [comment]
Error logs from after first snapshot: https://gist.github.com/adamsilverstein/79f8feb6994f974c60585494f94759c9

**Comment by tlovett1** [comment]
@adamsilverstein just pushed something to the WPA master branch. Can you test?

**Comment by adamsilverstein** [comment]
@tlovett1 still seeing the same issue in travis (https://travis-ci.org/10up/distributor/builds/517412820?utm_source=github_status&utm_medium=notification) - where the secondary machines don't load correctly. Also seeing some test failures that seem new I can try to work on. Testing locally.

**Comment by adamsilverstein** [comment]
@tlovett1 Woohoo! that did it, I see Travis running the tests against each machine now. Once these pass I can merge and then start adding some Gutenberg specific tests.

**Comment by adamsilverstein** [comment]
Tests are green against all snapshots!

**Comment by adamsilverstein** [comment]
Block tests aren't passing yet, I'll work on those in a follow up PR.

**Pull request merged**
